import React from "react";
import EstruturaPagina from "../../../componentes/EstruturaPaginas";
import '../estilo.css';

export default function Jogo() {
    return (
        <EstruturaPagina>
            <div className="texto-limitado">
                <h1 className="titulo">Jogo</h1>
                <p>San Andreas está estruturado de maneira similar aos dois jogos anteriores da série Grand Theft Auto. A parte central do jogo consiste de elementos de um jogo de corrida combinado com um third-person shooter, e um ambiente aberto e livre que permite ao jogador interagir e se locomover. A pé, o personagem controlado pelo jogador é capaz de andar, nadar e mergulhar (O primeiro jogo da série na qual isto é possível), escalar e pular, além de usar armas e se envolver em diversos tipos de combates manuais. Os jogadores também podem controlar diversos tipos de veículos, incluindo automóveis, caminhões, barcos, aviões, helicópteros, trens, tanque de guerra, motocicletas e bicicletas. O sistema de jogo aberto e não-linear permite aos jogadores explorar e escolher como desejam jogar o jogo exatamente. Embora as missões da trama sejam necessárias para o progresso através do jogo, e para destravar outras cidades (Todas áreas rurais; San Fierro; deserto e por último Las Venturas) e algum conteúdo do jogo, elas não são obrigatórias, e os jogadores podem completá-las quando quiser, e simplesmente vagar pelos territórios quando não as estiverem cumprindo. No entanto, criar muitos conflitos podem atrair atração indesejada - e potencialmente fatal - das autoridades; quanto mais caos causado, mais intensa a resposta: a polícia cuida das infrações menos graves, como ataque a transeuntes, apontar armas em locais públicos, roubo de carros, alguns assassinatos, enquanto equipes da SWAT, do FBI e até mesmo o exército americano respondem a distúrbios mais graves.</p>

                <p>O jogador também pode participar de diversas missões opcionais; entre elas estão as tradicionais missões adicionais dos jogos anteriores, como dirigir um táxi e conduzir passageiros pela cidade, apagar incêndios com um carro de bombeiro, dirigir uma ambulância pela cidade e combater o crime, como justiceiro. Entre as novas adições estão missões onde o jogador pode desempenhar a função de ladrão de residência (Arrombamento) ou cafetão, fazer entregas de carga através de trens e caminhões, e frequentar auto escola; moto escola; escola náutica e especialização em aviação - onde ele ainda pode desenvolver sua habilidade em muitos dos veículos existentes no jogo.</p>

                <p>Ao contrário de GTA Vice City e GTA III, que precisavam interromper o jogo para carregar mais dados sempre que o jogador se deslocava para distritos diferentes da cidade, o GTA: San Andreas não apresenta nenhum tipo de espera enquanto o jogador está se movimentando, já que seu mapa é muito maior que o dos jogos anteriores. As únicas cenas de carregamento no jogo são para ilustrar interlúdios ou antes de mostrar os interiores dos ambientes. Algumas outras diferenças entre o San Andreas e seus predecessores estão a possibilidade de multijogador nas chamadas missões Rampage, e a mudança dos 'pacotes secretos' dos antecessores por pichações, fotografias, ferraduras e ostras que podem ser feitas ou coletadas pelo jogador para desbloquear kits de armamentos, cada casa segura tem um conjunto diferente de "ferramentas".</p>

                <p>Os controles de câmera, das lutas e do posicionamento do alvo das armas de fogo foram retrabalhados, de maneira a incorporar conceitos de outro jogo da Rockstar, Manhunt, incluindo diversos elementos de ações sigilosas, assim como miras melhoradas e um mostrador da saúde do personagem, que muda de cor verde para vermelho ou negro dependendo do seu estado. A versão para PC ainda implementou acordes de mouse; o jogador deve segurar o botão direito do mouse para ativar a mira, e então clicar ou segurar o botão esquerdo para atirar ou utilizar algum item, como uma câmera fotográfica.</p>

                <p>O jogador pode, pela primeira vez na série, nadar e subir em muros ou paredes. A capacidade de nadar tem um grande efeito no personagem também, já que a água pela primeira vez não representa uma barreira impedindo a sua locomoção pelo cenário. Para um poder de fogo maior, os jogadores também podem ter duas armas ao mesmo tempo, ou fazer um tiroteio de dentro de um veículo (Drive-by shooting), com outros membros da gangue. Devido ao imenso tamanho do mapa de San Andreas, uma marcação pode ser adicionada ao mapa HUD que é visualizado na tela, auxiliando o jogador a chegar a um destino.</p>

                <p>A inteligência artificial do jogo também foi muito melhorada em relação a seus antecessores. O jogador não pode mais, por exemplo, espancar até à morte algum transeunte numa rua movimentada, em plena luz do dia, sem que haja alguma reação do público. Enquanto a maioria dos pedestres, por exemplo, pode fugir ou se esconder, alguns civis armados (Como traficantes de drogas ou membros de outras gangues) podem atacar CJ, ao que os membros da gangue de CJ podem responder fogo e perseguir seus oponentes. Os policiais agora também perseguem personagens não-controlados pelo jogador que estejam cometendo crimes.</p>
            </div>
        </EstruturaPagina>
    );
}
